### ISSUE TITLE
修改为本地面板，重启后控制面板显示”404 page not found" 

### ISSUE THREAD

**Issue by toraidl** [Dashboard2/Dashboard#1]
请问本地面板模块是解压到什么地方的呢？ 该如何解决这个问题。

**Comment by ghost** [comment]
如果您使用的模块为 [CPFM](https://github.com/kalasutra/Clash_Premium_For_Magisk)，可能是由于模块没有真正重启导致的，请尝试使用停止稍后启动的方式来重启模块，或者多次停止来暂时关闭模块，或者直接重启手机系统。

解压目录位于配置文件同目录，但本现象并非解压失败导致，如果解压失败，预期行为仍然为加载在线面板。
